# Generated by Django 4.0.3 on 2022-04-01 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcplCalander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=150, null=True)),
                ('team', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('emp_name', models.CharField(max_length=300)),
                ('emp_id', models.CharField(max_length=50)),
                ('emp_desi', models.CharField(max_length=100)),
                ('att_actual', models.CharField(max_length=50)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('appoved_by', models.CharField(blank=True, max_length=300, null=True)),
                ('rm1', models.CharField(blank=True, max_length=200, null=True)),
                ('rm2', models.CharField(blank=True, max_length=200, null=True)),
                ('rm3', models.CharField(blank=True, max_length=200, null=True)),
                ('rm1_id', models.CharField(blank=True, max_length=30, null=True)),
                ('rm2_id', models.CharField(blank=True, max_length=30, null=True)),
                ('rm3_id', models.CharField(blank=True, max_length=30, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=150, null=True)),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_name', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('pl_balance', models.FloatField()),
                ('sl_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='leaveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=150, null=True)),
                ('emp_id', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('leave_type', models.CharField(max_length=30)),
                ('transaction', models.CharField(max_length=30)),
                ('no_days', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=150, null=True)),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=50)),
                ('emp_desi', models.CharField(max_length=50)),
                ('emp_process', models.CharField(max_length=50)),
                ('leave_type', models.CharField(max_length=50)),
                ('applied_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_days', models.IntegerField()),
                ('agent_reason', models.TextField(blank=True, null=True)),
                ('tl_approval', models.BooleanField(default=False)),
                ('tl_status', models.CharField(blank=True, max_length=50, null=True)),
                ('tl_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('manager_approval', models.BooleanField(default=False)),
                ('manager_reason', models.TextField(blank=True, null=True)),
                ('manager_status', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_rm1', models.CharField(max_length=200)),
                ('emp_rm2', models.CharField(max_length=200)),
                ('emp_rm3', models.CharField(max_length=200)),
                ('emp_rm1_id', models.CharField(max_length=50)),
                ('emp_rm2_id', models.CharField(max_length=50)),
                ('emp_rm3_id', models.CharField(max_length=50)),
                ('escalation', models.BooleanField(default=False)),
                ('escalation_reason', models.TextField(blank=True, null=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='media/SL_Proof')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_desi', models.CharField(max_length=200)),
                ('emp_rm1', models.CharField(max_length=200)),
                ('emp_rm1_id', models.CharField(max_length=30)),
                ('emp_rm2', models.CharField(max_length=200)),
                ('emp_rm2_id', models.CharField(max_length=30)),
                ('emp_rm3', models.CharField(max_length=200)),
                ('emp_rm3_id', models.CharField(max_length=30)),
                ('emp_process', models.CharField(max_length=200)),
                ('emp_process_id', models.CharField(max_length=10)),
                ('pc', models.BooleanField(default=False)),
                ('img', models.ImageField(default='media/user_images/user.png', upload_to='media/user_images')),
                ('doj', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('on_id', models.IntegerField(blank=True, null=True)),
                ('agent_status', models.CharField(default='Active', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
